import type { UBCalendarCategory } from "./UBCalendarView"
import type { UBFullCalendarEvent } from "./UBFullCalendarView"
import type { UBListEventViewProps } from "./UBListEventView"

export const sharedCalendarCategories: UBCalendarCategory[] = [
  { id: "academic", label: "Academic", color: "#5b2db8" },
  { id: "sports", label: "Sports", color: "#e0a702" },
  { id: "career", label: "Career", color: "#3b82f6" },
  { id: "cultural", label: "Cultural", color: "#ec4899" },
  { id: "research", label: "Research", color: "#10b981" },
  { id: "workshop", label: "Workshop", color: "#f97316" },
]

export const sharedCalendarEvents: UBFullCalendarEvent[] = [
  {
    id: "e-jan-1",
    date: "2026-01-14",
    categoryId: "academic",
    title: "Spring Semester Orientation",
    time: "09:00",
    location: "Main Campus Auditorium",
    secondaryActionLabel: "Add to Google Calendar",
  },
  {
    id: "e-feb-1",
    date: "2026-02-21",
    categoryId: "cultural",
    title: "Belize Arts and Heritage Showcase",
    time: "18:30",
    location: "Open Air Theatre",
    secondaryActionLabel: "Add to Google Calendar",
  },
  {
    id: "e-mar-1",
    date: "2026-03-08",
    categoryId: "research",
    title: "Marine Research Methods Symposium",
    time: "10:00",
    location: "Belize Marine Institute",
    secondaryActionLabel: "Add to Google Calendar",
  },
  {
    id: "e-apr-1",
    date: "2026-04-12",
    categoryId: "career",
    title: "Career Readiness Bootcamp",
    time: "13:30",
    location: "FMNS Courtyard",
    secondaryActionLabel: "Add to Google Calendar",
  },
  {
    id: "event-1",
    date: "2026-05-28",
    categoryId: "workshop",
    title: "Workshop: Intro to Machine Learning with Python",
    time: "14:00",
    location: "FST Computer Lab B",
    secondaryActionLabel: "Add to Google Calendar",
  },
  {
    id: "event-2",
    date: "2026-05-29",
    categoryId: "academic",
    title: "Open Lecture: Indigenous Knowledge in Modern Curricula",
    time: "16:00",
    location: "Faculty of Education Hall",
    secondaryActionLabel: "Add to Google Calendar",
  },
  {
    id: "event-3",
    date: "2026-05-30",
    categoryId: "sports",
    title: "Jaguars vs. UWI Pelicans - CFU Semifinal",
    time: "19:00",
    location: "Marion Jones Stadium",
    secondaryActionLabel: "Add to Google Calendar",
  },
  {
    id: "e-jun-1",
    date: "2026-06-08",
    categoryId: "cultural",
    title: "Garifuna Settlement Day Cultural Night",
    time: "18:30",
    location: "Open Air Theatre",
    secondaryActionLabel: "Add to Google Calendar",
  },
  {
    id: "e-jul-1",
    date: "2026-07-19",
    categoryId: "workshop",
    title: "Summer Coding Lab",
    time: "11:00",
    location: "FST Computer Lab B",
    secondaryActionLabel: "Add to Google Calendar",
  },
  {
    id: "e-aug-1",
    date: "2026-08-25",
    categoryId: "sports",
    title: "Interfaculty Athletics Meet",
    time: "16:00",
    location: "Marion Jones Stadium",
    secondaryActionLabel: "Add to Google Calendar",
  },
  {
    id: "e-sep-1",
    date: "2026-09-04",
    categoryId: "academic",
    title: "Faculty Research Colloquium",
    time: "15:00",
    location: "Education Hall",
    secondaryActionLabel: "Add to Google Calendar",
  },
  {
    id: "e-oct-1",
    date: "2026-10-10",
    categoryId: "career",
    title: "Belize Tech and Tourism Career Fair",
    time: "10:00",
    location: "FMNS Courtyard",
    secondaryActionLabel: "Add to Google Calendar",
  },
  {
    id: "e-nov-1",
    date: "2026-11-22",
    categoryId: "research",
    title: "Calabash Caye Field Day",
    time: "07:00",
    location: "Calabash Caye Field Station",
    secondaryActionLabel: "Add to Google Calendar",
  },
  {
    id: "e-dec-1",
    date: "2026-12-05",
    categoryId: "cultural",
    title: "End of Year Cultural Festival",
    time: "17:00",
    location: "Belmopan Campus Grounds",
    secondaryActionLabel: "Add to Google Calendar",
  },
]

export const sharedListEvents: UBListEventViewProps["events"] = [
  {
    id: "event-1",
    month: "May",
    day: 28,
    category: "Workshop",
    secondaryCategory: "UB Computing Society",
    title: "Workshop: Intro to Machine Learning with Python",
    time: "14:00",
    location: "FST Computer Lab B",
    addToCalendarLabel: "Add to Google Calendar",
  },
  {
    id: "event-2",
    month: "May",
    day: 29,
    category: "Academic",
    secondaryCategory: "Faculty of Education",
    title: "Open Lecture: Indigenous Knowledge in Modern Curricula",
    time: "16:00",
    location: "Faculty of Education Hall",
    addToCalendarLabel: "Add to Google Calendar",
  },
  {
    id: "event-3",
    month: "Jun",
    day: 8,
    category: "Cultural",
    secondaryCategory: "UB Cultural Council",
    title: "Garifuna Settlement Day Cultural Night",
    time: "18:30",
    location: "Open Air Theatre",
    addToCalendarLabel: "Add to Google Calendar",
  },
]

export const sharedCalendarMonth = new Date(2026, 4, 1)
export const sharedCalendarSelectedDate = new Date(2026, 4, 28)
